name: Node.js CI 

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v4 
    
    - name: Usar Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'

    - name: Instalar dependências
      run: npm install 

    - name: Testar Conexão (Dry Run)
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }} 
      run: node db.js 
